const Car = require('../car');

module.exports = {
  1: [["red",2,[2, 0],"right"], ["green",3,[0, 3],"up"]],
  2: [[ "red", 2, [2, 0], "right"],
    [ "green", 3, [0, 2], "up"],
    [ "blue", 2, [4, 1], "right"],
    [ "orange", 2, [5, 1], "right"]],
  3: [["red", 2, [2, 0], "right"],
    [ "green", 2, [2, 2], "up"],
    [ "black", 2, [0, 0], "up"],
    [ "yellow", 2, [4, 2], "up"],
    [ "purple", 2, [0 ,2], "right"],
    [ "blue", 2, [1, 2], "right"],
    [ "teal", 2, [0, 4], "up"],
    [ "lightgreen", 2, [0, 5], "up"]],
  4: [[ "red", 2, [2, 0], "right"],
    [ "green", 3, [0, 2], "up"],
    [ "blue", 3, [4, 0], "right"],
    [ "orange", 3, [5, 0], "right"],
    [ "lightgreen", 2, [3, 4], "up"],
    [ "teal", 2, [1, 4], "right"]],
  5: [[ "red", 2, [2, 2], "right"],
    [ "orange", 3, [0, 4], "up"],
    [ "blue", 3, [0, 1], "right"],
    [ "lightgreen", 2, [0, 0], "up"],
    [ "yellow", 2, [2, 0], "up"],
    [ "gray", 3, [4, 0], "right"],
    [ "purple", 2, [3, 3], "up"],
    [ "black", 2, [3, 4], "right"],
    [ "green", 2, [5, 3], "right"],
    [ "lightblue", 2, [5, 0], "right"]],
  6: [[ "red", 2, [2, 0], "right"],
    [ "blue", 2, [3, 0], "right"],
    [ "lightgreen", 2, [1, 4], "up"],
    [ "yellow", 3, [2, 2], "up"],
    [ "purple", 2, [5, 2], "right"],
    [ "green", 2, [0, 2], "up"],
    [ "teal", 2, [0, 3], "right"],
    [ "orange", 2, [3, 4], "up"],
    [ "black", 2, [5, 4], "right"]],
  7: [[ "red", 2, [2, 1], "right"],
    [ "blue", 2, [0, 0], "up"],
    [ "lightblue", 3, [0, 3], "right"],
    [ "yellow", 2, [1, 1], "right"],
    [ "purple", 2, [1, 3], "up"],
    [ "green", 2, [3, 0], "up"],
    [ "teal", 2, [3, 1], "up"],
    [ "orange", 2, [5, 1], "right"],
    [ "black", 3, [4, 2], "right"],
    [ "lightgreen", 2, [5, 3], "right"],
    [ "gold", 3, [1, 4], "up"]],
  8: [[ "red", 2, [2, 3], "right"],
    [ "blue", 2, [0, 5], "up"],
    [ "lightblue", 2, [0, 0], "up"],
    [ "yellow", 2, [0, 4], "up"],
    [ "green", 2, [2, 1], "up"],
    [ "orange", 3, [1, 1], "right"],
    [ "gray", 3, [2, 5], "up"],
    [ "teal", 2, [3, 0], "up"],
    [ "purple", 2, [4, 1], "up"],
    [ "lightgreen", 3, [2, 2], "up"],
    [ "pink", 2, [5, 4], "right"],
    [ "black", 2, [0, 1], "right"],
    [ "brown", 3, [3, 3], "up"]],
  9: [[ "red", 2, [2, 0], "right"],
    [ "blue", 2, [0, 1], "up"],
    [ "lightblue", 3, [0, 2], "up"],
    [ "yellow", 3, [0, 3], "right"],
    [ "purple", 2, [1, 4], "up"],
    [ "gray", 2, [4, 4], "right"],
    [ "green", 2, [4, 0], "up"],
    [ "black", 2, [5, 1], "right"],
    [ "teal", 2, [3, 0], "right"],
    [ "lightgreen", 2, [2, 3], "up"],
    [ "pink", 3, [5, 3], "right"]],
  10: [[ "red", 2, [2, 2], "right"],
    [ "blue", 2, [0, 3], "right"],
    [ "yellow", 2, [2, 4], "up"],
    [ "purple", 2, [4, 4], "up"],
    [ "gray", 2, [0, 2], "up"],
    [ "green", 2, [3, 2], "right"],
    [ "lightgreen", 2, [0, 0], "up"],
    [ "black", 3, [3, 5], "up"],
    [ "lightblue", 2, [3, 0], "right"],
    [ "pink", 2, [4, 1], "up"],
    [ "teal", 2, [4, 2], "right"]],
  11: [[ "red", 2, [2, 0], "right"],
    [ "blue", 3, [0, 3], "right"],
    [ "purple", 2, [1, 5], "up"],
    [ "gray", 2, [1, 4], "up"],
    [ "green", 2, [3, 4], "right"],
    [ "black", 2, [0, 2], "up"],
    [ "lightblue", 2, [3, 0], "up"],
    [ "pink", 2, [5, 0], "right"],
    [ "yellow", 2, [4, 1], "right"],
    [ "lightgreen", 2, [0, 1], "up"],
    [ "teal", 2, [3, 1], "right"],
    [ "orange", 2, [4, 4], "up"]],
  12: [[ "red", 2, [2, 1], "right"],
  [ "blue", 2, [0, 0], "up"],
  [ "purple", 3, [0, 3], "up"],
  [ "gray", 2, [0, 4], "right"],
  [ "green", 2, [1, 4], "up"],
  [ "black", 2, [3, 2], "up"],
  [ "lightblue", 3, [3, 5], "up"],
  [ "pink", 2, [4, 1], "up"],
  [ "teal", 2, [4, 3], "right"]]
};
